# Generated by Django 3.0.5 on 2020-04-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0002_auto_20200419_0508'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='post',
            index_together={('id', 'slug')},
        ),
    ]
