# Generated by Django 3.0.5 on 2020-04-24 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0004_auto_20200424_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 10, 13, 9, 640957, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 10, 13, 9, 641010, tzinfo=utc)),
        ),
    ]
