# Generated by Django 3.0.5 on 2020-04-24 11:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0006_auto_20200424_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
