# Generated by Django 3.0.5 on 2020-04-24 11:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspace', '0008_auto_20200424_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
        ),
    ]
